"""
Definizione dei 38 corsi formativi ufficiali estratti dal Catalogo CIFIGE 2022-2024.
Include durate (settimane e ore), requisiti di sicurezza, propedeuticità formative,
precedenti operativi, selezioni, competenze linguistiche e altri requisiti specifici.
"""

CIFIGE_COURSES = [
    {
        "codice_corso": "CIFIGE-01",
        "denominazione": "Corso Intelligence Interforze",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Nessuno (Corso d'accesso base al comparto)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna selezione prevista",
        "conoscenza_lingua": "Standard",
        "altri_requisiti": "Destinato a personale di nuova assegnazione al settore intelligence",
        "prerequisiti": "NOS Riservato; nessuna selezione o corso propedeutico vincolante.",
        "descrizione": "Fornire le conoscenze fondamentali sulle finalità, l'organizzazione e le procedure operative del comparto intelligence interforze."
    },
    {
        "codice_corso": "CIFIGE-02",
        "denominazione": "Corso J2 Staff",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna selezione prevista",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8 (2/2/2/2)",
        "altri_requisiti": "Destinato a Ufficiali e Sottufficiali impiegati in branche J2/G2/A2/N2",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze; Lingua: NATO JFLT 8.",
        "descrizione": "Addestrare il personale destinato agli staff J2/A2/G2/N2 nelle procedure di pianificazione operativa e supporto informativo di livello operativo/tattico."
    },
    {
        "codice_corso": "CIFIGE-03",
        "denominazione": "Corso Analista Intelligence",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 4,
        "durata_ore": 144,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso J2 Staff (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna selezione prevista",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8 (2/2/2/2)",
        "altri_requisiti": "Personale addetto a cellule di analisi informativa",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso J2 Staff; Lingua: NATO JFLT 8.",
        "descrizione": "Specializzare il personale nelle metodologie avanzate di analisi informativa, tecniche di pensiero strutturato e redazione di dossier d'intelligence."
    },
    {
        "codice_corso": "CIFIGE-04",
        "denominazione": "Corso Intelligence Leader",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Analista Intelligence (obbligatorio)",
        "precedenti_operativi": "Esperienza direttiva in cellule o reparti d'intelligence",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8 (2/2/2/2)",
        "altri_requisiti": "Destinato a Capi Sezione/Ufficio e Quadri Direttivi",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Analista Intelligence; Lingua: NATO JFLT 8.",
        "descrizione": "Approfondire la leadership, la gestione del ciclo di produzione informativa e il coordinamento di team complessi di analisi."
    },
    {
        "codice_corso": "CIFIGE-05",
        "denominazione": "Corso TECHINT 1° Livello",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Competenze tecniche di base nel settore armamenti e materiali",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze; Lingua: NATO JFLT 8.",
        "descrizione": "Fornire la preparazione fondamentale sulle tecniche di analisi dell'intelligence tecnica su materiali ed equipaggiamenti d'armamento."
    },
    {
        "codice_corso": "CIFIGE-06",
        "denominazione": "Corso TECHINT 2° Livello",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso TECHINT 1° Livello (obbligatorio)",
        "precedenti_operativi": "Impiego operativo in unità o cellule di valutazione tecnica",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso TECHINT 1° Livello; Lingua: NATO JFLT 8.",
        "descrizione": "Approfondire lo sfruttamento scientifico e tecnico dei sistemi d'arma complessi, minacce non convenzionali e reverse engineering hardware."
    },
    {
        "codice_corso": "CIFIGE-07",
        "denominazione": "Corso OSINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Buone competenze nell'uso della rete Internet e ricerca web",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze; Lingua: NATO JFLT 8.",
        "descrizione": "Addestrare alle metodologie di ricerca, raccolta, verifica e analisi informativa da fonti aperte e banche dati digitali."
    },
    {
        "codice_corso": "CIFIGE-08",
        "denominazione": "Corso Social Media OSINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze e Corso OSINT (obbligatori)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze + Corso OSINT; Lingua: NATO JFLT 8.",
        "descrizione": "Specializzare nell'acquisizione e analisi informativa derivante da piattaforme social network, forum online e piattaforme di messaggistica istantanea."
    },
    {
        "codice_corso": "CIFIGE-09",
        "denominazione": "Corso Analista OSINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze, Corso OSINT, Corso Social Media OSINT (obbligatori)",
        "precedenti_operativi": "Almeno 12 mesi di impiego operativo continuativo in disciplina OSINT",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Attestazione di impiego continuativo del Comando di appartenenza",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze + OSINT + Social Media OSINT; 12 mesi impiego operativo OSINT; Lingua: NATO JFLT 8.",
        "descrizione": "Abilitare alla produzione analitica integrata di livello strategico basata esclusivamente o prevalentemente sul patrimonio informativo da fonti aperte."
    },
    {
        "codice_corso": "CIFIGE-10",
        "denominazione": "Corso Attività Informative Difensive Staff (A.I.D.)",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO SLP non inferiore a 8",
        "altri_requisiti": "Destinato a personale di staff per il supporto alla controminaccia",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze; Lingua: NATO SLP 8.",
        "descrizione": "Procedure di staff per la pianificazione, coordinamento e monitoraggio delle attività informative difensive e controspionaggio militare."
    },
    {
        "codice_corso": "CIFIGE-11",
        "denominazione": "Corso Attività Informative Difensive Operatore (A.I.D.)",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Superamento prove selettive protocollo fonti umane (ed. 2021)",
        "conoscenza_lingua": "Standard",
        "altri_requisiti": "Idoneità fisica SMI; valutazione caratteristica >= 'Superiore alla Media' ultimi 5 anni; nessuna sanzione di rigore o condanna penale",
        "prerequisiti": "NOS Segreto/NATO Secret; Selezioni protocollo fonti umane 2021; Propedeutico: Corso Intelligence Interforze; Note caratteristiche >= Superiore alla Media; Idoneità SMI.",
        "descrizione": "Addestramento operativo sul campo per operatori dediti all'acquisizione di sicurezza e protezione da minacce ostili."
    },
    {
        "codice_corso": "CIFIGE-12",
        "denominazione": "Corso Operatore HUMINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Superamento prove selettive protocollo fonti umane (ed. 2021)",
        "conoscenza_lingua": "Standard (auspicabile conoscenza seconda lingua)",
        "altri_requisiti": "Patente Militare Mod. 2; idoneità fisica SMI; valutazione caratteristica >= 'Superiore alla Media' ultimi 5 anni; assenza di procedimenti penali o sanzioni di rigore",
        "prerequisiti": "NOS Segreto/NATO Secret; Patente Militare Mod. 2; Selezioni protocollo fonti umane 2021; Propedeutico: Corso Intelligence Interforze; Note caratteristiche >= Superiore alla Media.",
        "descrizione": "Qualificare operatori dedicati alle attività di ricerca e contatto con fonti umane per l'intelligence tattica e operativa."
    },
    {
        "codice_corso": "CIFIGE-13",
        "denominazione": "Corso SIGINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Conoscenze di base di telecomunicazioni e propagazione elettromagnetica",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze; Lingua: NATO JFLT 8.",
        "descrizione": "Nozioni e procedure d'impiego operativo nel dominio Signals Intelligence (intercettazione e analisi delle emissioni elettromagnetiche)."
    },
    {
        "codice_corso": "CIFIGE-14",
        "denominazione": "Corso Analista COMINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segretissimo / NATO COSMIC Top Secret",
        "precedenti_formativi": "Corso SIGINT (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Destinato a reparti specialistici d'intercettazione comunicazioni",
        "prerequisiti": "NOS Segretissimo/NATO COSMIC Top Secret; Propedeutico: Corso SIGINT; Lingua: NATO JFLT 8.",
        "descrizione": "Specializzazione nell'analisi tecnica e contenutistica dei flussi di comunicazioni intercettati (COMINT)."
    },
    {
        "codice_corso": "CIFIGE-15",
        "denominazione": "Corso Analista Dati Digitali COMINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Analista COMINT (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Analista COMINT; Lingua: NATO JFLT 8.",
        "descrizione": "Tecniche avanzate di elaborazione e correlazione su grandi moli di metadati e comunicazioni digitali complesse."
    },
    {
        "codice_corso": "CIFIGE-16",
        "denominazione": "Corso Analista ELINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso SIGINT (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Conoscenza fisica radar ed emissioni radioelettriche non di comunicazione",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso SIGINT; Lingua: NATO JFLT 8.",
        "descrizione": "Analisi dei parametri e catalogazione delle emissioni radar e dei segnali elettromagnetici non vocali."
    },
    {
        "codice_corso": "CIFIGE-17",
        "denominazione": "Corso Ricerca Elettronica Aerotrasportata",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segretissimo / NATO Cosmic Top Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Almeno 3 anni di impiego continuativo presso il CII",
        "selezioni": "Idoneità psicofisica al volo (IMAS - Aeronautica Militare) e all. F SMD-RIS/001-03",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Personale destinato a svolgere mansioni operative a bordo di piattaforme aeree",
        "prerequisiti": "NOS Segretissimo/NATO Cosmic Top Secret; Idoneità al volo IMAS; Propedeutico: Corso Intelligence Interforze; 3 anni impiego CII; Lingua: NATO JFLT 8.",
        "descrizione": "Addestramento all'impiego dei sensori di guerra elettronica e intelligence a bordo di vettori aerotrasportati."
    },
    {
        "codice_corso": "CIFIGE-18",
        "denominazione": "Corso ACINT",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Destinato al comparto marittimo/subacqueo",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze; Lingua: NATO JFLT 8.",
        "descrizione": "Principi e metodologie di acoustic intelligence subacquea per l'identificazione di bersagli navali e sottomarini."
    },
    {
        "codice_corso": "CIFIGE-19",
        "denominazione": "Corso ACINT Avanzato",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze e Corso Operatore ACINT c/o SMD-RIS/CII",
        "precedenti_operativi": "Esperienza pregressa su sensori sonar",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze + Corso Operatore ACINT CII; Lingua: NATO JFLT 8.",
        "descrizione": "Analisi spettrale avanzata e classificazione acustica per operatori analisti del dominio marittimo."
    },
    {
        "codice_corso": "CIFIGE-20",
        "denominazione": "Corso Applicativo COMINT Convenzionale",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Corso SIGINT (auspicabile)",
        "precedenti_operativi": "Attività specialistica morse (almeno 3 mesi) certificata da CII/GrAI",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Conoscenza codice telegrafico e trasmissione convenzionale",
        "prerequisiti": "NOS Riservato; Corso SIGINT auspicabile; Attività morse (3 mesi) certificata CII/GrAI; Lingua: NATO JFLT 8.",
        "descrizione": "Applicazioni pratiche di intercettazione e decodifica di segnali radio convenzionali HF/VHF."
    },
    {
        "codice_corso": "CIFIGE-21",
        "denominazione": "Corso Ufficiali Designati RME",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 7,
        "durata_ore": 252,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Adeguato all'impiego",
        "precedenti_formativi": "Nessuno",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Inserimento in elenco nominativo approvato da SMD/FFAA",
        "conoscenza_lingua": "Standard",
        "altri_requisiti": "Ufficiali specificamente designati dai rispettivi Stati Maggiori",
        "prerequisiti": "NOS Adeguato; Designazione nominativa approvata SMD/FFAA.",
        "descrizione": "Formazione specialistica per Ufficiali destinati a funzioni direttive nei Reparti Militari Elicotteristici (RME)."
    },
    {
        "codice_corso": "CIFIGE-22",
        "denominazione": "Corso Sottufficiali (Coadiutori) Designati RME",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 6,
        "durata_ore": 216,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Adeguato all'impiego",
        "precedenti_formativi": "Nessuno",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Candidature indicate dalle rispettive Forze Armate",
        "conoscenza_lingua": "Standard",
        "altri_requisiti": "Sottufficiali designati dai Comandi di Forza Armata",
        "prerequisiti": "NOS Adeguato; Candidature designate Forze Armate.",
        "descrizione": "Addestramento dei coadiutori e sottufficiali destinati a incarichi operativi e logistici nei reparti RME."
    },
    {
        "codice_corso": "CIFIGE-23",
        "denominazione": "Corso Carabinieri Addetti Vigilanza RME",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 4,
        "durata_ore": 144,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Adeguato all'impiego",
        "precedenti_formativi": "Nessuno",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Segnalazione nominativa del Comando Generale dell'Arma dei Carabinieri",
        "conoscenza_lingua": "Standard",
        "altri_requisiti": "Militari dell'Arma dei Carabinieri destinati alla vigilanza RME",
        "prerequisiti": "NOS Adeguato; Candidature Comando Generale CC.",
        "descrizione": "Procedure speciali di sicurezza fisica, controllo e vigilanza armata per le installazioni elicotteristiche."
    },
    {
        "codice_corso": "CIFIGE-24",
        "denominazione": "Corso Propedeutico CNO",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Nessuno",
        "precedenti_operativi": "Competenze informatiche di base",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Competenze informatiche base; Lingua: NATO JFLT 8.",
        "descrizione": "Introduzione ai concetti, alla dottrina e alle capacità nelle Computer Network Operations (CNO) militari."
    },
    {
        "codice_corso": "CIFIGE-25",
        "denominazione": "Corso Acquisizione Forense",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Nessuno",
        "precedenti_operativi": "Conoscenze informatiche base e pacchetto Office",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Conoscenze informatiche base; Lingua: NATO JFLT 8.",
        "descrizione": "Metodologie di repertamento e acquisizione 'forensic-sound' di evidenze digitali da memorie di massa e dispositivi mobili."
    },
    {
        "codice_corso": "CIFIGE-26",
        "denominazione": "Corso Analisi Forense",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 5,
        "durata_ore": 180,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Corso Acquisizione Forense (obbligatorio)",
        "precedenti_operativi": "Conoscenze approfondite sistemi operativi Windows",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Propedeutico: Corso Acquisizione Forense; SO Windows; Lingua: NATO JFLT 8.",
        "descrizione": "Esame approfondito e ricostruzione forense delle attività utente su sistemi digitali, analisi del file system e artefatti di sistema."
    },
    {
        "codice_corso": "CIFIGE-27",
        "denominazione": "Corso Penetration Testing",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 5,
        "durata_ore": 180,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Corso Acquisizione Forense (obbligatorio)",
        "precedenti_operativi": "Competenze in networking, sistemi Linux, linguaggi di scripting e database SQL",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Propedeutico: Corso Acquisizione Forense; Competenze Linux/networking/SQL; Lingua: NATO JFLT 8.",
        "descrizione": "Tecniche di vulnerability assessment e test di penetrazione difensivo su reti telematiche e infrastrutture informatiche."
    },
    {
        "codice_corso": "CIFIGE-28",
        "denominazione": "Corso Web Exploitation",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 5,
        "durata_ore": 180,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Corso Penetration Testing (auspicabile)",
        "precedenti_operativi": "Competenze CISCO ICND1, ambienti Linux, web application security, SQL, bash",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Corso Penetration Testing auspicabile; Competenze web app/SQL/Linux; Lingua: NATO JFLT 8.",
        "descrizione": "Identificazione ed analisi delle vulnerabilità di applicazioni web, standard OWASP e tecniche di messa in sicurezza."
    },
    {
        "codice_corso": "CIFIGE-29",
        "denominazione": "Corso Reverse Engineering",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 4,
        "durata_ore": 144,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Corso Web Exploitation (auspicabile)",
        "precedenti_operativi": "Conoscenza approfondita virtualizzazione VMWare, linguaggio C e Assembler",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Corso Web Exploitation auspicabile; Linguaggio C/Assembler/VMWare; Lingua: NATO JFLT 8.",
        "descrizione": "Disassemblaggio, decompilazione ed analisi statica/dinamica di codice binario per la comprensione del funzionamento di malware."
    },
    {
        "codice_corso": "CIFIGE-30",
        "denominazione": "Corso Analista Cyber Intelligence",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO SECRET",
        "precedenti_formativi": "Corso Intelligence Interforze e Corso Penetration Testing (obbligatori)",
        "precedenti_operativi": "Almeno 1 anno di impiego continuativo presso il CII",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze + Penetration Testing; 1 anno impiego CII; Lingua: NATO JFLT 8.",
        "descrizione": "Valutazione strategica e tattica delle minacce informatiche statuali e non, APT e campagne di disinformazione cyber."
    },
    {
        "codice_corso": "CIFIGE-31",
        "denominazione": "Corso Mobile Forensic Intelligence",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO SECRET",
        "precedenti_formativi": "Corso Intelligence Interforze e Corso Acquisizione Forense (obbligatori; auspicabile COMINT o CYBINT o CNO)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze + Acquisizione Forense; Lingua: NATO JFLT 8.",
        "descrizione": "Estrazione e decodifica di database e comunicazioni criptate da dispositivi mobili (smartphone, tablet, tracker GPS)."
    },
    {
        "codice_corso": "CIFIGE-32",
        "denominazione": "Corso Web Exploitation Intelligence",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Analista Cyber Intelligence e Corso Web Exploitation (obbligatori; auspicabile CNO)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Analista CYBINT + Web Exploitation; Lingua: NATO JFLT 8.",
        "descrizione": "Sfruttamento avanzato delle vulnerabilità web a fini informativi e intelligence nel dominio cibernetico."
    },
    {
        "codice_corso": "CIFIGE-33",
        "denominazione": "Corso Reverse Engineering Intelligence",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Analista Cyber Intelligence e Corso Reverse Engineering (obbligatori; auspicabile CNO)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Analista CYBINT + Reverse Engineering; Lingua: NATO JFLT 8.",
        "descrizione": "Attribuzione di attacchi informatici mediante de-offuscamento e reverse engineering di impianti cyber ostili."
    },
    {
        "codice_corso": "CIFIGE-34",
        "denominazione": "Corso Analisi Rischio Sanitario Ambientale (MEDINT)",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Corso Intelligence Interforze (auspicabile) e qualifica specialistica NBC",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Test d'ingresso",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Destinato a Ufficiali medici/sanitari o analisti specializzati NBC",
        "prerequisiti": "NOS Riservato; Test d'ingresso; Corso Intelligence Interforze e qualifica NBC auspicabili; Lingua: NATO JFLT 8.",
        "descrizione": "Valutazione dei fattori di rischio biologico, chimico, epidemico ed ambientale per la salute delle forze in Teatro Operativo."
    },
    {
        "codice_corso": "CIFIGE-35",
        "denominazione": "Corso Valorizzazione di Medical Information",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Corso Intelligence Interforze (auspicabile) e qualifica NBC",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Corso Intelligence Interforze e qualifica NBC auspicabili; Lingua: NATO JFLT 8.",
        "descrizione": "Integrazione delle informazioni sanitarie nella pianificazione operativa di supporto informativo alle missioni."
    },
    {
        "codice_corso": "CIFIGE-36",
        "denominazione": "Corso Istruttore Intelligence Militare",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio)",
        "precedenti_operativi": "Almeno 24 mesi di impiego certificato in discipline intelligence (Patria o Teatro Operativo); laurea universitaria auspicabile",
        "selezioni": "Superamento moduli didattici ISMA/CIFIGE",
        "conoscenza_lingua": "Standard",
        "altri_requisiti": "Spiccate attitudini alla docenza e comunicazione istituzionale",
        "prerequisiti": "NOS Segreto/NATO Secret; Corso Intelligence Interforze; 24 mesi impiego intelligence; Moduli didattici ISMA/CIFIGE.",
        "descrizione": "Qualificazione pedagogica e metodologica per docenti e formatori del Centro Interforze di Formazione Intelligence."
    },
    {
        "codice_corso": "CIFIGE-37",
        "denominazione": "Corso Sicurezza e Tutela delle Informazioni",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 1,
        "durata_ore": 36,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Riservato",
        "precedenti_formativi": "Nessuno",
        "precedenti_operativi": "Personale incaricato della trattazione e custodia di documenti e dati riservati",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Standard",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Riservato; Personale addetto alla tutela del segreto.",
        "descrizione": "Normativa nazionale e NATO in materia di tutela del segreto, INFOSEC, classificazione atti e bonifiche."
    },
    {
        "codice_corso": "CIFIGE-38",
        "denominazione": "Corso Intelligence Fusion and Threat Network Analysis (IFTNA)",
        "ente_erogatore": "Centro Interforze di Formazione Intelligence/G.E. (CIFI/GE)",
        "durata_settimane": 2,
        "durata_ore": 72,
        "validita_mesi": None,
        "requisiti_sicurezza": "NOS Segreto / NATO Secret",
        "precedenti_formativi": "Corso Intelligence Interforze (obbligatorio); Corso TECHINT 1° Livello (auspicabile)",
        "precedenti_operativi": "Nessuno",
        "selezioni": "Nessuna",
        "conoscenza_lingua": "Livello NATO JFLT non inferiore a 8",
        "altri_requisiti": "Nessuno",
        "prerequisiti": "NOS Segreto/NATO Secret; Propedeutico: Corso Intelligence Interforze obbligatorio, TECHINT 1° Livello auspicabile; Lingua: NATO JFLT 8.",
        "descrizione": "Metodologie avanzate di fusione multi-disciplinare e mappatura di reti di minaccia asimmetriche ed ibride."
    }
]

